version: "3.1"

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_URL: 'mongodb://database:27017'
      MONGO_DBNAME: 'microblog'
      STORAGE_MODE: 'inmemory'

  database:
    image: mongo:4.4
    ports:
      - 27017:27017